# Generated by Django 5.2.11 on 2026-02-03 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="quote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="quotes.quote",
            ),
        ),
        migrations.AddField(
            model_name="projectmedia",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="projects.project",
            ),
        ),
    ]
