# Generated by Django 5.2.11 on 2026-02-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CALL", "Llamada"),
                            ("WHATSAPP", "WhatsApp"),
                            ("EMAIL", "Email"),
                            ("VISIT", "Visita"),
                            ("TASK", "Tarea"),
                        ],
                        default="TASK",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Actividad",
                "verbose_name_plural": "Actividades",
                "ordering": ["-due_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("WEB", "Página Web"),
                            ("IG", "Instagram"),
                            ("WHATSAPP", "WhatsApp"),
                            ("REFERRAL", "Referido"),
                            ("OTHER", "Otro"),
                        ],
                        default="OTHER",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Nuevo"),
                            ("QUALIFIED", "Calificado"),
                            ("DISQUALIFIED", "Descartado"),
                            ("CONVERTED", "Convertido"),
                        ],
                        default="NEW",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("NEW", "Nuevo"),
                            ("CONTACTED", "Contactado"),
                            ("VISIT_SCHEDULED", "Visita Agendada"),
                            ("QUOTE_SENT", "Cotización Enviada"),
                            ("NEGOTIATION", "En Negociación"),
                            ("WON", "Ganado"),
                            ("LOST", "Perdido"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "value_estimate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("close_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Oportunidad",
                "verbose_name_plural": "Oportunidades",
                "ordering": ["-created_at"],
            },
        ),
    ]
